version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html # Add this line
    links:
      - nodejs
      - html
    depends_on:
      - nodejs
      - html

  nodejs:
    image: node:latest
    working_dir: /home
    volumes:
      - ./nodejs:/home # Add this line
    command: "npm start"

  html:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
